model: CatBoostClassifier

hyperparameters:
  classifier__n_estimators: [100, 200, 300]
  classifier__depth: [3,4,5]
  classifier__learning_rate: [0.001, 0.01, 0.1]
  classifier__min_data_in_leaf: [10, 20, 30]
